apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: keycloak
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: apisix-dashboard
    chartVersion: 0.6.0

  # helmVersion identifies the Helm Version used to render the Chart. Default is v2.
  helmVersion: v3

  # useHelmInstall identifies whether this Helm chart will use the
  # Replicated Helm installation (false) or native Helm installation (true). Default is false.
  # Native Helm installations are only available for Helm v3 charts.
  useHelmInstall: true

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    replicaCount: repl{{ ConfigOption "dashboard-replica-count" | ParseInt }}
    someCoolFeature: repl{{ LicenseFieldValue "some-cool-feature-enabled" }}

  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder: {}