apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: keycloak-application
spec:
  selector:
    matchLabels:
      kots.io/app-slug: keycloak-application
  addOwnerRef: true
  descriptor:
    links:
      - description: About
        url: 'https://bitnami.com/stack/keycloak/helm'
    version: '15.1.3'
    description: 'SettleMint'
    icons:
      - src: 'https://res.cloudinary.com/practicaldev/image/fetch/s--I1k_5qM---/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://thepracticaldev.s3.amazonaws.com/i/dp51une42j0d8uas60cx.png'
        type: 'image/png'
        size: '512x512'
