apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: keycloak-config
spec:
  groups:

    

    - name: keycloak_group
      title: Keycloak
      items:
        - name: keycloak
          type: select_one
          title: Type
          required: true
          help_text: Would you like to use an embedded Keycloak instance, or connect to an external instance that you manage?
          items:
            - name: keycloak_embedded
              title: Embedded
            - name: keycloak_external
              title: External

        - name: keycloak_admin_user
          title: Admin user (email address)
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_embedded"}}'
          type: text
          required: true
          default: "support@settlemint.com"

        - name: keycloak_admin_password
          title: Admin password
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_embedded"}}'
          type: password
          required: true

        - name: keycloak_client_id
          title: Client ID
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_external"}}'
          type: text
          required: true

        - name: keycloak_client_secret
          title: Client Secret
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_external"}}'
          type: password
          required: true

        - name: keycloak_realm
          title: Realm URI
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_external"}}'
          type: text
          required: true

        - name: keycloak_resources
          type: select_one
          title: Resources
          help_text: How much resources would you like to allocate to the Keycloak instance?
          default: keycloak_resources_default
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_embedded"}}'
          items:
            - name: keycloak_resources_default
              title: Default
            - name: keycloak_resources_custom
              title: Custom

        - name: resources_keycloak_request_cpu
          type: text
          title: CPU Request
          default: '250m'
          value: '250m'
          required: true
          when: '{{repl ConfigOptionEquals "keycloak_resources" "keycloak_resources_custom"}}'
        - name: resources_keycloak_limit_cpu
          type: text
          title: CPU Limit
          default: '2000m'
          value: '2000m'
          when: '{{repl ConfigOptionEquals "keycloak_resources" "keycloak_resources_custom"}}'
        - name: resources_keycloak_request_memory
          type: text
          title: Memory Request
          default: '512Mi'
          value: '512Mi'
          required: true
          when: '{{repl ConfigOptionEquals "keycloak_resources" "keycloak_resources_custom"}}'
        - name: resources_keycloak_limit_memory
          type: text
          title: Memory Limit
          default: '1024Mi'
          value: '1024Mi'
          required: true
          when: '{{repl ConfigOptionEquals "keycloak_resources" "keycloak_resources_custom"}}'

    - name: postgres_group
      title: Postgresql
      items:
        - name: postgres_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"

        - name: postgres
          type: select_one
          title: Type
          required: true
          help_text: Would you like to use an embedded postgres instance, or connect to an external instance that you manage?
          items:
            - name: postgres_embedded
              title: Embedded
            - name: postgres_external
              title: External

        - name: postgres_host
          title: Postgres Host
          when: '{{repl ConfigOptionEquals "postgres" "postgres_external"}}'
          default: 'localhost'
          type: text
          required: true
        - name: postgres_port
          title: Postgres Port
          when: '{{repl ConfigOptionEquals "postgres" "postgres_external"}}'
          type: text
          default: '5432'
          required: true
        - name: postgres_user
          title: Postgres Username
          when: '{{repl ConfigOptionEquals "postgres" "postgres_external"}}'
          type: text
          default: "postgres"
          required: true
        - name: external_postgres_password
          title: Postgres Password
          default: '{{repl ConfigOption "postgres_password"}}'
          when: '{{repl ConfigOptionEquals "postgres" "postgres_external"}}'
          type: password
          required: true
        - name: postgres_db
          title: Postgres Database
          when: '{{repl ConfigOptionEquals "postgres" "postgres_external"}}'
          type: text
          required: true
          default: settlemint
          value: settlemint

        - name: postgres_disk_size
          title: Disk size
          type: text
          required: true
          help_text: How much disk space should be provisioned for the postgres instance? (e.g. 20Gi)
          when: '{{repl ConfigOptionEquals "postgres" "postgres_embedded"}}'

        - name: postgres_resources
          type: select_one
          title: Resources
          help_text: How much resources would you like to allocate to the postgres instance?
          default: postgres_resources_default
          when: '{{repl ConfigOptionEquals "postgres" "postgres_embedded"}}'
          items:
            - name: postgres_resources_default
              title: Default
            - name: postgres_resources_custom
              title: Custom

        - name: resources_postgres_request_cpu
          type: text
          title: CPU Request
          default: '250m'
          value: '250m'
          required: true
          when: '{{repl ConfigOptionEquals "postgres_resources" "postgres_resources_custom"}}'
        - name: resources_postgres_limit_cpu
          type: text
          title: CPU Limit
          default: '1000m'
          value: '1000m'
          required: true
          when: '{{repl ConfigOptionEquals "postgres_resources" "postgres_resources_custom"}}'
        - name: resources_postgres_request_memory
          type: text
          title: Memory Request
          default: '256Mi'
          value: '256Mi'
          required: true
          when: '{{repl ConfigOptionEquals "postgres_resources" "postgres_resources_custom"}}'
        - name: resources_postgres_limit_memory
          type: text
          title: Memory Limit
          default: '1024Mi'
          value: '1024Mi'
          required: true
          when: '{{repl ConfigOptionEquals "postgres_resources" "postgres_resources_custom"}}'

    - name: redisgroup
      title: Redis
      items:
        - name: redis_password
          hidden: true
          type: password
          value: '{{repl RandomString 32}}'

        - name: redis
          type: select_one
          title: Type
          required: true
          help_text: Would you like to use an embedded Redis instance, or connect to an external instance that you manage?
          items:
            - name: redis_embedded
              title: Embedded
            - name: redis_external
              title: External

        - name: redis_host
          title: Redis Host
          when: '{{repl ConfigOptionEquals "redis" "redis_external"}}'
          type: text
          required: true
          default: 'localhost'
        - name: redis_port
          title: Redis Port
          when: '{{repl ConfigOptionEquals "redis" "redis_external"}}'
          type: text
          default: '6379'
          required: true
        - name: redis_user
          title: Redis Username
          when: '{{repl ConfigOptionEquals "redis" "redis_external"}}'
          default: 'default'
          type: text
          required: true
        - name: external_redis_password
          title: Redis Password
          when: '{{repl ConfigOptionEquals "redis" "redis_external"}}'
          type: password
          default: '{{repl ConfigOption "redis_password"}}'
          required: true
        - name: redis_disk_size
          title: Disk size
          type: text
          required: true
          help_text: How much disk space should be provisioned for the redis instance? (e.g. 10Gi)
          when: '{{repl ConfigOptionEquals "redis" "redis_embedded"}}'

        - name: redis_resources
          type: select_one
          title: Resources
          help_text: How much resources would you like to allocate to the redis instance?
          when: '{{repl ConfigOptionEquals "redis" "redis_embedded"}}'
          default: redis_resources_default
          items:
            - name: redis_resources_default
              title: Default
            - name: redis_resources_custom
              title: Custom

        - name: resources_redis_request_cpu
          type: text
          title: CPU Request
          default: '100m'
          value: '100m'
          required: true
          when: '{{repl ConfigOptionEquals "redis_resources" "redis_resources_custom"}}'
        - name: resources_redis_limit_cpu
          type: text
          title: CPU Limit
          default: '500m'
          value: '500m'
          required: true
          when: '{{repl ConfigOptionEquals "redis_resources" "redis_resources_custom"}}'
        - name: resources_redis_request_memory
          type: text
          title: Memory Request
          default: '128Mi'
          value: '128Mi'
          required: true
          when: '{{repl ConfigOptionEquals "redis_resources" "redis_resources_custom"}}'
        - name: resources_redis_limit_memory
          type: text
          title: Memory Limit
          default: '512Mi'
          value: '512Mi'
          required: true
          when: '{{repl ConfigOptionEquals "redis_resources" "redis_resources_custom"}}'

    - name: promgroup
      title: Prometheus
      items:
        - name: prometheus
          type: select_one
          title: Type
          help_text: Would you like to use an embedded Prometheus instance, or connect to an external instance that you manage? Note that using embedded Prometheus will deploy a Cluster level role and role binding.
          required: true
          items:
            - name: prometheus_embedded
              title: Embedded
            - name: prometheus_external
              title: External

        - name: prometheus_endpoint
          title: Prometheus Endpoint
          when: '{{repl ConfigOptionEquals "prometheus" "prometheus_external"}}'
          type: text
          required: true

        - name: prometheus_disk_size
          title: Disk size
          type: text
          required: true
          help_text: How much disk space should be provisioned for the Prometheus instance? (e.g. 10Gi)
          when: '{{repl ConfigOptionEquals "prometheus" "prometheus_embedded"}}'

        - name: prometheus_resources
          type: select_one
          title: Resources
          help_text: How much resources would you like to allocate to the prometheus instance?
          when: '{{repl ConfigOptionEquals "prometheus" "prometheus_embedded"}}'
          default: prometheus_resources_default
          items:
            - name: prometheus_resources_default
              title: Default
            - name: prometheus_resources_custom
              title: Custom

        - name: resources_prometheus_request_cpu
          type: text
          title: CPU Request
          default: '300m'
          value: '300m'
          required: true
          when: '{{repl ConfigOptionEquals "prometheus_resources" "prometheus_resources_custom"}}'
        - name: resources_prometheus_limit_cpu
          type: text
          title: CPU Limit
          default: '2000m'
          value: '2000m'
          required: true
          when: '{{repl ConfigOptionEquals "prometheus_resources" "prometheus_resources_custom"}}'
        - name: resources_prometheus_request_memory
          type: text
          title: Memory Request
          default: '1536Mi'
          value: '1536Mi'
          required: true
          when: '{{repl ConfigOptionEquals "prometheus_resources" "prometheus_resources_custom"}}'
        - name: resources_prometheus_limit_memory
          type: text
          title: Memory Limit
          default: '2560Mi'
          value: '2560Mi'
          required: true
          when: '{{repl ConfigOptionEquals "prometheus_resources" "prometheus_resources_custom"}}'

    - name: vaultgroup
      title: Hashicorp Vault
      items:
        - name: vault
          type: select_one
          title: Type
          required: true
          help_text: Would you like to use an embedded Vault instance, or connect to an external instance that you manage?
          items:
            - name: vault_embedded
              title: Embedded
            - name: vault_external_oss
              title: External (OSS)
            - name: vault_external_enterprise
              title: External (Enterprise)

        - name: vault_host
          title: Vault Endpoint
          when: '{{repl or (ConfigOptionEquals "vault" "vault_external_oss") (ConfigOptionEquals "vault" "vault_external_enterprise")}}'
          type: text
          required: true
        - name: vault_role_id
          title: Vault Role ID
          when: '{{repl or (ConfigOptionEquals "vault" "vault_external_oss") (ConfigOptionEquals "vault" "vault_external_enterprise")}}'
          type: text
          required: true
        - name: vault_secret_id
          title: Vault Secret ID
          when: '{{repl or (ConfigOptionEquals "vault" "vault_external_oss") (ConfigOptionEquals "vault" "vault_external_enterprise")}}'
          type: password
          required: true
        - name: vault_namespace
          title: Vault Namespace
          when: '{{repl ConfigOptionEquals "vault" "vault_external_enterprise"}}'
          type: text
          required: true
        - name: vault_ethereum_path
          title: Ethereum secrets path
          when: '{{repl or (ConfigOptionEquals "vault" "vault_external_oss") (ConfigOptionEquals "vault" "vault_external_enterprise")}}'
          type: text
          default: "ethereum"
          required: true
        - name: vault_ipfs_path
          title: IPFS secrets path
          when: '{{repl or (ConfigOptionEquals "vault" "vault_external_oss") (ConfigOptionEquals "vault" "vault_external_enterprise")}}'
          type: text
          default: "ipfs"
          required: true

        - name: vault_resources
          type: select_one
          title: Resources
          help_text: How much resources would you like to allocate to the vault instance?
          when: '{{repl ConfigOptionEquals "vault" "vault_embedded"}}'
          default: vault_resources_default
          items:
            - name: vault_resources_default
              title: Default
            - name: vault_resources_custom
              title: Custom

        - name: resources_vault_request_cpu
          type: text
          title: CPU Request
          default: '100m'
          value: '100m'
          required: true
          when: '{{repl ConfigOptionEquals "vault_resources" "vault_resources_custom"}}'
        - name: resources_vault_limit_cpu
          type: text
          title: CPU Limit
          default: '1000m'
          value: '1000m'
          required: true
          when: '{{repl ConfigOptionEquals "vault_resources" "vault_resources_custom"}}'
        - name: resources_vault_request_memory
          type: text
          title: Memory Request
          default: '512Mi'
          value: '512Mi'
          required: true
          when: '{{repl ConfigOptionEquals "vault_resources" "vault_resources_custom"}}'
        - name: resources_vault_limit_memory
          type: text
          title: Memory Limit
          default: '1024Mi'
          value: '1024Mi'
          required: true
          when: '{{repl ConfigOptionEquals "vault_resources" "vault_resources_custom"}}'

    - name: ingressgroup
      title: Ingress
      items:
        - name: ingress_custom_ingress_host
          title: FQDN to access the SettleMint platform
          required: true
          type: text
        - name: ingress_class
          title: A custom ingress class, if this value is empty 'openshift' is used on an OpenShift cluster and 'nginx' on a Kubernetes cluster
          required: false
          type: text
        - name: ingress_tls
          type: bool
          title: Use TLS on all ingress/routes
          default: "1"
        - name: ingress_additional_annotations
          title: Additional Annotations
          type: textarea
          help_text: |
            Use this textarea to provide additional annotations specific to your environment.
            For example: cert-utils-operator.redhat-cop.io/certs-from-secret: 'my-cert'.

    - name: secretsgroup
      title: Secret Management
      items:
        - name: secret_extra_env_vars
          title: Secretname containing extra or overriding environment variables
          placeholder: "extra-secrets"
          type: text
        - name: secret_additional_deployment_annotations
          title: Additional Deployment/Job/StatefulSet Annotations
          type: textarea
          help_text: |
            Use this textarea to provide additional annotations specific to your environment.
            For example:
              vault.hashicorp.com/agent-inject-secret-truststore-jks: "secret/path/to/secret/truststore_jks"
              vault.hashicorp.com/agent-inject-file-truststore-jks: truststore.jks
