apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: keycloak-config
spec:
  groups:
    - name: keycloak_group
      title: Keycloak
      items:
        - name: keycloak
          type: select_one
          title: Type
          required: true
          help_text: Would you like to use an embedded Keycloak instance, or connect to an external instance that you manage?
          items:
            - name: keycloak_embedded
              title: Embedded
            - name: keycloak_external
              title: External

        - name: keycloak_admin_user
          title: Admin user (email address)
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_embedded"}}'
          type: text
          required: true
          default: "support@replicated.com"

        - name: keycloak_admin_password
          title: Admin password
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_embedded"}}'
          type: password
          required: true

        - name: keycloak_client_id
          title: Client ID
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_external"}}'
          type: text
          required: true

        - name: keycloak_client_secret
          title: Client Secret
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_external"}}'
          type: password
          required: true

        - name: keycloak_realm
          title: Realm URI
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_external"}}'
          type: text
          required: true

        - name: keycloak_resources
          type: select_one
          title: Resources
          help_text: How much resources would you like to allocate to the Keycloak instance?
          default: keycloak_resources_default
          when: '{{repl ConfigOptionEquals "keycloak" "keycloak_embedded"}}'
          items:
            - name: keycloak_resources_default
              title: Default
            - name: keycloak_resources_custom
              title: Custom

        - name: resources_keycloak_request_cpu
          type: text
          title: CPU Request
          default: '250m'
          value: '250m'
          required: true
          when: '{{repl ConfigOptionEquals "keycloak_resources" "keycloak_resources_custom"}}'
        - name: resources_keycloak_limit_cpu
          type: text
          title: CPU Limit
          default: '2000m'
          value: '2000m'
          when: '{{repl ConfigOptionEquals "keycloak_resources" "keycloak_resources_custom"}}'
        - name: resources_keycloak_request_memory
          type: text
          title: Memory Request
          default: '512Mi'
          value: '512Mi'
          required: true
          when: '{{repl ConfigOptionEquals "keycloak_resources" "keycloak_resources_custom"}}'
        - name: resources_keycloak_limit_memory
          type: text
          title: Memory Limit
          default: '1024Mi'
          value: '1024Mi'
          required: true
          when: '{{repl ConfigOptionEquals "keycloak_resources" "keycloak_resources_custom"}}'